development:
  adapter: postgresql
  encoding: unicode
  database: ouro
  pool: 5
  username: postgres
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: ouro
  pool: 5
  username: postgres
  password: 